## General pipeline parameters:

# working directory:
# Within this directory, directory called "F3UTER_preictions" would be generated
workdir: ""

# directory containing F3UTER omic feature files
features_dir: ""

# prefix of all output files
sample_name: ""

# path to ER file or BED file which was used to generate features [input file to "generate_features"]
ers: ""
